application: langbot-stage
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: img/favicon.png
  upload: img/favicon\.png  

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /remoteapi.*
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: langbot_main.py


