application: langbot-stage
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: images/favicon.png
  upload: images/favicon\.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /styles
  static_dir: styles
  
- url: /images
  static_dir: images
    
- url: /.*
  script: langbot_main.py

